# Generated by Django 3.0.5 on 2020-04-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionSymptom',
            fields=[
                ('symptomId', models.IntegerField(primary_key=True, serialize=False)),
                ('conditionId', models.IntegerField()),
                ('relevanceScore', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('symptomId', 'conditionId')},
            },
        ),
    ]
