# Generated by Django 3.0.5 on 2020-04-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0002_conditionsymptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercondition',
            name='conditionId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercondition',
            name='insertedData',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conditionsymptom',
            name='conditionId',
            field=models.IntegerField(default=0),
        ),
    ]
